# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
      PGDATA: /data/postgres
    ports:
      - "5432:5432"